test:
  prop: testValue

server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssmp?useSSL=false&useServerPrepStmts=true
      username: root
      password: 1234
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb1_
      #      配置id为自增模式
      id-type: auto

configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


testcase:
  book:
    id: ${random.int}
    id2: ${random.int(10)}
    type: ${random.int(5,10)}
    name: 黑马${random.value}
    uuid: ${random.uuid}
    publishTime: ${random.long}


