server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: nacos:8848
    gateway:
      routes: #网关路由配置
        - id: user-service #路由id 自定义 只要唯一即可
        #uri http://127.0.0.1:8081 #路由目标地址 http就是固定地址
          uri: lb://userservice #路由的目标地址 lb就是负载均衡 后面根服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** #这个是按照路径匹配 只要以/user/开头就符合要求
            #- After=2031-01-20T17:42:47.789-07:00[America/Denver] #在这个时间之前符合要求  https://docs.spring.io/spring-cloud-gateway/docs/2.2.10.BUILD-SNAPSHOT/reference/html/#gateway-request-predicates-factories
          filters: #放在一项下是对一个服务有效果 让在与routes同一级就对全部服务起效果
            - AddRequestHeader=Truth, zsh is freaking aowsome!
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
      default-filters: #放在一项下是对一个服务有效果 让在与routes同一级就对全部服务起效果
        - AddRequestHeader=Truth, zsh is freaking aowsome!
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期