server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: nacos:8848
      discovery:
        cluster-name: HZ #设置集群名称
#        namespace: d5a28da1-f9eb-4c86-af73-f9868c8ea419 #命名空间 填Id 服务在一个命名空间中才可以互通
        #  ephemeral: false #默认是true 即临时实例 非临时实例在nacos中 即使服务被停止 也不会被剔除
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


userservice:
  ribbon:
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #负载均衡规则 这条配置用于让一个集群内的请求只会去找一个集群的服务
#    eager-load:
#      enabled: true #开启饥饿加载
#      clients: userservice #指定对对userservice这个服务饥饿加载
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: basic

feign:
  httpclient:
    enabled: true #支持httpclient的开关
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
